# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a774a46a66c76e22b4e361daa7ba3c45000f67bdfcc650ca5a41aac3ac753f410c5081bc9983842f37724b712c47ccba49f5ca8da99b18b467883e08ea3eae05

test:
  secret_key_base: 25b825b609fbfc48e150116b305e7b45f793b3a09b3fe4acac36e915e83e0786381a8b786272c22b4b0316abb015e98ee379192a609dd51de36e9222665f3009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
